window.INITIAL_DATA = {
  "version": 15,
  "groupName": "可愛綿羊咩咩區",
  "leaders": {
    "pastor": "Amber",
    "districtLeader": "AUYAN",
    "leader": "Zachary",
    "deputy": "Tom"
  },
  "members": [
    {
      "id": "peter",
      "name": "Peter",
      "gender": "男",
      "spiritualScore": 99.8,
      "birthday": "2001-08-08",
      "age": "24歲",
      "job": "帷幕工程師",
      "location": "大安（國父紀念館）",
      "relationship": "單身",
      "joinedAt": "2024-03-01",
      "tenure": "2年4個月",
      "attendanceRate": 79,
      "faith": "已受洗",
      "service": "核心同工",
      "devotion": "穩定且固定時間",
      "prayerLife": "穩定且深入",
      "stability": "非常穩定且主動",
      "bible": "有系統讀經中",
      "hunger": "願意主動追求",
      "spiritualState": "穩定成長中",
      "lastInterview": "2026-05-05",
      "nextInterview": "2026-08-03",
      "status": "在組",
      "role": "小組員",
      "notes": "",
      "faithGeneration": "3代（含）以上",
      "serviceDetail": "Hope Kids",
      "serviceBonus": 3,
      "pressureSources": [
        "無明顯壓力"
      ],
      "familyRelationship": "融洽穩定",
      "interpersonalRelationship": "穩定良好",
      "wellbeing": "穩定良好",
      "temptations": [
        "拖延"
      ],
      "breakthroughs": [
        "更願意悔改",
        "開始面對問題"
      ],
      "stuckPoints": [
        "暫無明顯卡住"
      ],
      "baptismDate": ""
    },
    {
      "id": "owen",
      "name": "Owen",
      "gender": "男",
      "spiritualScore": 94.2,
      "birthday": "1997-08-11",
      "age": "28歲",
      "job": "工程師",
      "location": "士林（圓山）",
      "relationship": "單身",
      "joinedAt": "2024-03-01",
      "tenure": "2年4個月",
      "attendanceRate": 51,
      "faith": "已受洗",
      "service": "穩定參與",
      "devotion": "穩定且固定時間",
      "prayerLife": "常願意為人代禱",
      "stability": "非常穩定且主動",
      "bible": "有系統讀經中",
      "hunger": "願意主動追求",
      "spiritualState": "穩定成長中",
      "lastInterview": "2026-06-10",
      "nextInterview": "2026-09-08",
      "status": "在組",
      "role": "小組員",
      "notes": "",
      "faithGeneration": "初代",
      "serviceDetail": "音控",
      "serviceBonus": 3,
      "pressureSources": [
        "屬靈低潮"
      ],
      "familyRelationship": "融洽穩定",
      "interpersonalRelationship": "穩定良好",
      "wellbeing": "穩定良好",
      "temptations": [
        "懶散被動"
      ],
      "breakthroughs": [
        "暫無明顯突破"
      ],
      "stuckPoints": [
        "內在控告",
        "反覆軟弱"
      ],
      "baptismDate": ""
    },
    {
      "id": "ryan",
      "name": "Ryan",
      "gender": "男",
      "spiritualScore": 87.9,
      "birthday": "1996-01-03",
      "age": "30歲",
      "job": "調酒師",
      "location": "士林（圓山）",
      "relationship": "單身",
      "joinedAt": "2024-03-01",
      "tenure": "2年4個月",
      "attendanceRate": 60,
      "faith": "已受洗",
      "service": "暫停服事中",
      "devotion": "穩定且固定時間",
      "prayerLife": "常願意為人代禱",
      "stability": "非常穩定且主動",
      "bible": "幾乎每天閱讀",
      "hunger": "願意主動追求",
      "spiritualState": "穩定成長中",
      "lastInterview": "2026-04-27",
      "nextInterview": "2026-07-26",
      "status": "在組",
      "role": "小組員",
      "notes": "",
      "faithGeneration": "初代",
      "serviceDetail": "Home場佈",
      "serviceBonus": 2,
      "pressureSources": [
        "未來方向",
        "感情"
      ],
      "familyRelationship": "融洽穩定",
      "interpersonalRelationship": "穩定良好",
      "wellbeing": "穩定良好",
      "temptations": [
        "焦慮憂心",
        "金錢壓力"
      ],
      "breakthroughs": [
        "更能信靠神",
        "禱告更真實"
      ],
      "stuckPoints": [
        "暫無明顯卡住"
      ],
      "baptismDate": ""
    },
    {
      "id": "shire",
      "name": "Shire",
      "gender": "男",
      "spiritualScore": 83.3,
      "birthday": "1996-05-29",
      "age": "30歲",
      "job": "侍酒師",
      "location": "文山（景美）",
      "relationship": "單身",
      "joinedAt": "2026-05-30",
      "tenure": "0年1個月",
      "attendanceRate": 100,
      "faith": "已受洗",
      "service": "尚未參與",
      "devotion": "幾乎每天",
      "prayerLife": "常願意為人代禱",
      "stability": "穩定出席",
      "bible": "跟著聚會進度",
      "hunger": "願意主動追求",
      "spiritualState": "穩定成長中",
      "lastInterview": "2026-06-07",
      "nextInterview": "2026-09-05",
      "status": "在組",
      "role": "小組員",
      "notes": "",
      "faithGeneration": "1代",
      "serviceDetail": "",
      "serviceBonus": 0,
      "pressureSources": [
        "工作"
      ],
      "familyRelationship": "疏離",
      "interpersonalRelationship": "穩定良好",
      "wellbeing": "待了解",
      "temptations": [
        "焦慮憂心",
        "人際敏感",
        "容易受傷"
      ],
      "breakthroughs": [
        "工作／課業更有節奏"
      ],
      "stuckPoints": [
        "待了解"
      ],
      "baptismDate": ""
    },
    {
      "id": "zachary",
      "name": "Zachary",
      "role": "組長",
      "gender": "男",
      "spiritualScore": 79.3,
      "birthday": "2001-02-08",
      "age": "25歲",
      "job": "會計師",
      "location": "永和（永安）",
      "relationship": "單身",
      "joinedAt": "2024-09-18",
      "tenure": "1年9個月",
      "attendanceRate": 96,
      "faith": "已受洗",
      "service": "偶爾參與",
      "devotion": "偶爾",
      "prayerLife": "每週數次",
      "stability": "非常穩定且主動",
      "bible": "每週固定閱讀",
      "hunger": "很高",
      "spiritualState": "聚會穩定但生命需突破",
      "lastInterview": "2026-07-12",
      "nextInterview": "2026-10-10",
      "status": "在組",
      "notes": "",
      "faithGeneration": "初代",
      "serviceDetail": "Hope Kids",
      "serviceBonus": 3,
      "pressureSources": [
        "工作",
        "屬靈低潮",
        "自我期待",
        "時間管理"
      ],
      "familyRelationship": "融洽穩定",
      "interpersonalRelationship": "大致良好",
      "wellbeing": "大致穩定",
      "temptations": [
        "懶散被動",
        "容易逃避",
        "情慾試探",
        "屬靈冷淡"
      ],
      "breakthroughs": [
        "情緒較穩定"
      ],
      "stuckPoints": [
        "感情困擾",
        "屬靈冷淡",
        "工作／課業壓力",
        "反覆軟弱"
      ],
      "baptismDate": ""
    },
    {
      "id": "jessie",
      "name": "Jessie",
      "gender": "女",
      "spiritualScore": 76.3,
      "birthday": "2004-04-13",
      "age": "22歲",
      "job": "學生",
      "location": "古亭（公館）",
      "relationship": "單身",
      "joinedAt": "2024-09-08",
      "tenure": "1年10個月",
      "attendanceRate": 61,
      "faith": "已受洗",
      "service": "穩定參與",
      "devotion": "每週3-4次",
      "prayerLife": "幾乎每天",
      "stability": "大多數時間出席",
      "bible": "有系統讀經中",
      "hunger": "穩定",
      "spiritualState": "穩定成長中",
      "lastInterview": "2026-05-26",
      "nextInterview": "2026-08-24",
      "status": "在組",
      "role": "小組員",
      "notes": "",
      "faithGeneration": "3代（含）以上",
      "serviceDetail": "Hope Kids",
      "serviceBonus": 2,
      "pressureSources": [
        "工作",
        "家庭",
        "未來方向"
      ],
      "familyRelationship": "融洽穩定",
      "interpersonalRelationship": "穩定良好",
      "wellbeing": "穩定良好",
      "temptations": [
        "人際敏感",
        "焦慮憂心"
      ],
      "breakthroughs": [
        "靈修更穩定"
      ],
      "stuckPoints": [
        "暫無明顯卡住"
      ],
      "baptismDate": ""
    },
    {
      "id": "simone",
      "name": "Simone",
      "gender": "女",
      "spiritualScore": 69.3,
      "birthday": "1998-03-23",
      "age": "28歲",
      "job": "老師",
      "location": "中山（中山國小）",
      "relationship": "單身",
      "joinedAt": "2026-05-30",
      "tenure": "0年1個月",
      "attendanceRate": 100,
      "faith": "已受洗",
      "service": "尚未參與",
      "devotion": "最近中斷中",
      "prayerLife": "有需要時會禱告",
      "stability": "非常穩定且主動",
      "bible": "跟著聚會進度",
      "hunger": "願意主動追求",
      "spiritualState": "穩定成長中",
      "lastInterview": "2026-06-08",
      "nextInterview": "2026-09-06",
      "status": "在組",
      "role": "小組員",
      "notes": "",
      "faithGeneration": "1代",
      "serviceDetail": "",
      "serviceBonus": 0,
      "pressureSources": [
        "工作",
        "時間管理",
        "自我期待",
        "感情"
      ],
      "familyRelationship": "融洽穩定",
      "interpersonalRelationship": "穩定良好",
      "wellbeing": "身心疲累",
      "temptations": [
        "焦慮憂心",
        "容易自責",
        "情緒低落"
      ],
      "breakthroughs": [
        "聚會更穩定",
        "工作／課業更有節奏",
        "更能信靠神"
      ],
      "stuckPoints": [
        "委身不足",
        "工作／課業壓力",
        "感情困擾"
      ],
      "baptismDate": ""
    },
    {
      "id": "grace",
      "name": "Grace",
      "gender": "女",
      "spiritualScore": 67.3,
      "birthday": "2004-09-01",
      "age": "21歲",
      "job": "學生",
      "location": "大安（大安）",
      "relationship": "穩定交往中",
      "joinedAt": "2026-05-30",
      "tenure": "0年1個月",
      "attendanceRate": 100,
      "faith": "已受洗",
      "service": "尚未參與",
      "devotion": "每週1-2次",
      "prayerLife": "每週數次",
      "stability": "最近不穩定",
      "bible": "跟著聚會進度",
      "hunger": "願意主動追求",
      "spiritualState": "穩定成長中",
      "lastInterview": "2026-06-08",
      "nextInterview": "2026-09-06",
      "status": "在組",
      "role": "小組員",
      "notes": "",
      "faithGeneration": "1代",
      "serviceDetail": "",
      "serviceBonus": 0,
      "pressureSources": [
        "家庭",
        "感情",
        "自我期待"
      ],
      "familyRelationship": "融洽穩定",
      "interpersonalRelationship": "穩定良好",
      "wellbeing": "穩定良好",
      "temptations": [
        "人際敏感",
        "金錢壓力"
      ],
      "breakthroughs": [
        "開始面對問題"
      ],
      "stuckPoints": [
        "工作／課業壓力"
      ],
      "baptismDate": ""
    },
    {
      "id": "maggie",
      "name": "Maggie",
      "gender": "女",
      "spiritualScore": 63.8,
      "birthday": "1992-11-07",
      "age": "33歲",
      "job": "小學英文老師",
      "location": "信義（象山）",
      "relationship": "穩定交往中",
      "joinedAt": "2025-09-07",
      "tenure": "0年10個月",
      "attendanceRate": 69,
      "faith": "已受洗",
      "service": "尚未參與",
      "devotion": "每週3-4次",
      "prayerLife": "每週數次",
      "stability": "大多數時間出席",
      "bible": "跟著聚會進度",
      "hunger": "高",
      "spiritualState": "穩定成長中",
      "lastInterview": "2026-01-01",
      "nextInterview": "2026-04-01",
      "status": "在組",
      "role": "小組員",
      "notes": "",
      "faithGeneration": "初代",
      "serviceDetail": "",
      "serviceBonus": 0,
      "pressureSources": [],
      "familyRelationship": "融洽穩定",
      "interpersonalRelationship": "普通",
      "wellbeing": "",
      "temptations": [],
      "breakthroughs": [],
      "stuckPoints": [],
      "baptismDate": ""
    },
    {
      "id": "tom",
      "name": "Tom",
      "role": "副組長",
      "gender": "男",
      "spiritualScore": 59.0,
      "birthday": "2003-03-18",
      "age": "23歲",
      "job": "學生",
      "location": "信義（象山）",
      "relationship": "單身",
      "joinedAt": "2024-03-01",
      "tenure": "2年4個月",
      "attendanceRate": 65,
      "faith": "慕道中",
      "service": "暫停服事中",
      "devotion": "每週1-2次",
      "prayerLife": "有需要時會禱告",
      "stability": "穩定出席",
      "bible": "有系統讀經中",
      "hunger": "願意主動追求",
      "spiritualState": "信仰冷淡中",
      "lastInterview": "2026-05-06",
      "nextInterview": "2026-08-04",
      "status": "在組",
      "notes": "",
      "faithGeneration": "1代",
      "serviceDetail": "青年",
      "serviceBonus": 2,
      "pressureSources": [
        "人際",
        "課業",
        "家庭",
        "未來方向"
      ],
      "familyRelationship": "大致良好",
      "interpersonalRelationship": "缺乏連結",
      "wellbeing": "身心疲累",
      "temptations": [
        "拖延",
        "容易自責",
        "懶散被動",
        "焦慮憂心"
      ],
      "breakthroughs": [
        "開始面對問題"
      ],
      "stuckPoints": [
        "不願敞開",
        "感情困擾"
      ],
      "baptismDate": ""
    }
  ],
  "meetings": [
    {
      "id": "meeting-1",
      "date": "2025-05-08",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": false,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "英文多益",
        "Kim": "國考通過",
        "Jessie": "身體健康",
        "Tom": "媽媽身體",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-2",
      "date": "2025-05-15",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": false,
        "Kim": false,
        "Jessie": false,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "",
        "Kim": "",
        "Jessie": "",
        "Tom": "媽媽的身體健康、減肥順利",
        "Ryan": "感謝主澳洲旅遊一切順利平安、去韓國順利、找到適合的工作",
        "Owen": "新工作順順利利",
        "Peter": "感謝主在澳洲跟大家聚在一起、謝謝大家為研究所代禱",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-3",
      "date": "2025-05-30",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作、學業、感情、頭毛",
        "Kim": "考試",
        "Jessie": "期末考、希望可以救回來期中的小跌倒",
        "Tom": "專注力、爸媽健康、期末考、功課完成",
        "Ryan": "在考空少的路有神的保守",
        "Owen": "新工作、希望遇到屬靈的主管",
        "Peter": "跟神的關係、親近神、不要安逸忘記神",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-4",
      "date": "2025-06-12",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "未來的規劃、（學生、當兵、工作…）",
        "Kim": "考試壓力",
        "Jessie": "專案（學校的、工作的）、與各方利害關係人溝通",
        "Tom": "期末、生命的各種issue",
        "Ryan": "週日要上課，不能參加主日，但可以參加週六",
        "Owen": "工作",
        "Peter": "得到好的休息（hope kids)、調整生活步調、工作",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-5",
      "date": "2025-06-19",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "跟女友的關係禱告",
        "Kim": "奶奶的健康  你媽的眼睛  考試",
        "Jessie": "",
        "Tom": "期末睡過頭  求神看守   經濟狀況",
        "Ryan": "媽媽牙齒",
        "Owen": "",
        "Peter": "最近工作順利下班年一樣順順遂遂",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-6",
      "date": "2025-06-27",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": false,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作應付得來，感情交給上帝",
        "Kim": "",
        "Jessie": "清邁旅途平安",
        "Tom": "NTU 考試",
        "Ryan": "空服員上課吸收多一點",
        "Owen": "感冒快快好",
        "Peter": "",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-7",
      "date": "2025-07-04",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": false,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "七月可以順利完成該做事項",
        "Kim": "奶奶健康",
        "Jessie": "",
        "Tom": "",
        "Ryan": "澳洲教會的兒童營和同工有主同在也順利",
        "Owen": "工作的交接可以順利",
        "Peter": "七月順利服侍告一個段落，然後可以休息一下",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-8",
      "date": "2025-07-17",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "下禮拜要處理的工作、感情",
        "Kim": "奶奶的狀況與竣文自己的平安還有家人們的心靈",
        "Jessie": "",
        "Tom": "找到禱告",
        "Ryan": "希望明天家人去宜蘭逛街平安不要下雨",
        "Owen": "感謝明天放假，禱告生命還不錯，記住天天背起十字架，不要因為現在很好忘記他",
        "Peter": "很順利感謝主，七月穩定服事八月可以休息",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-9",
      "date": "2025-07-24",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": false,
        "Ryan": false,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作上、感情上很順利，會一起跟女友禱告，感謝主\n代禱:工作ending順利，感情一起走在信仰上，與Diane出遊順利",
        "Kim": "竣文在休息的季節能得到好好的休息",
        "Jessie": "去長勘島，旅途平安",
        "Tom": "",
        "Ryan": "",
        "Owen": "靈命都不錯，跟耶穌聊天很棒，很助眠，保持一個習慣",
        "Peter": "感謝神有時間休息，靈命成長更多",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-10",
      "date": "2025-07-31",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "safety on travels, Gospel to Girlfriend",
        "Kim": "personal state of mind and May the Lord be with their Family",
        "Jessie": "Family health",
        "Tom": "Get stuff done",
        "Ryan": "Safe travels for Diane and Zach",
        "Owen": "physical health, over-exercise",
        "Peter": "rest in august, finishing serving smoothly",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-11",
      "date": "2025-08-07",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": true,
        "Tom": false,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "work",
        "Kim": "",
        "Jessie": "parents’ health",
        "Tom": "",
        "Ryan": "TOEIC result",
        "Owen": "work",
        "Peter": "amily and personal relationship with God",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-12",
      "date": "2025-08-14",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作一切順利",
        "Kim": "奶奶、心情、工作、家人、國考",
        "Jessie": "",
        "Tom": "時間管理  父母溝通",
        "Ryan": "",
        "Owen": "",
        "Peter": "這一週一樣順利 好好休息",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-13",
      "date": "2025-08-21",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": true,
        "Tom": false,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作份量越來越重，希望可以應付的來。 感情方面，更多quality time.",
        "Kim": "",
        "Jessie": "爸媽身體禱告。 並且不要太擔心他們，心裡有平安。",
        "Tom": "",
        "Ryan": "為禮拜六禱告，不論結果如何，都希望是對台灣好！",
        "Owen": "工作， 人員積極性。",
        "Peter": "工作可以榮耀神。",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-14",
      "date": "2025-08-28",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "與女朋友可以好好理性談分開",
        "Kim": "",
        "Jessie": "開學一切順利",
        "Tom": "減肥、轉學",
        "Ryan": "鵬鵬加班順利結束",
        "Owen": "明天天氣很好",
        "Peter": "生活中可以活出基督的樣式、靈命成長、被神帶領",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-15",
      "date": "2025-09-04",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "Job",
        "Kim": "Zach’s love life, ability to Rest",
        "Jessie": "ability to Rest",
        "Tom": "轉學",
        "Ryan": "Professional Success: Flight Attendant",
        "Owen": "Business trip, safe travels",
        "Peter": "ability to Rest",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-16",
      "date": "2025-09-11",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": false,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "考核然後工作順遂",
        "Kim": "現在的狀態跟鵬鵬愛情",
        "Jessie": "工作上的平安",
        "Tom": "",
        "Ryan": "咳嗽 身體健康",
        "Owen": "",
        "Peter": "九月的休息",
        "Maggie": "與同事的關係、今晚有個安穩的睡眠",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-17",
      "date": "2025-09-18",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": false,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作順利、考核成功、為信仰禱告",
        "Kim": "希望狀態變好，經歷神，回到剛接觸信仰的火熱的狀態。",
        "Jessie": "希望神帶領自己面對和處理憤怒",
        "Tom": "",
        "Ryan": "為身體禱告，希望咳嗽快好",
        "Owen": "",
        "Peter": "希望大家的眼睛是明亮的，身體是被光照的。持續對焦上帝",
        "Maggie": "同事人際關係、睡得好。",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-18",
      "date": "2025-10-02",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": false,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "渴慕神、持續讀經",
        "Kim": "腦中的旋律禱告",
        "Jessie": "驅逐蟑螂、減肥",
        "Tom": "",
        "Ryan": "工作持續保守",
        "Owen": "",
        "Peter": "最後三個月服事禱告，給予充足的智慧，調配時間跟體力，足以應付 ，好讓有好的結束",
        "Maggie": "同事關係、心情",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-19",
      "date": "2025-10-09",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": false,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "有一顆敏銳的心察覺\n神的提醒跟旨意,當好管\n家,還有努力在路上快和解",
        "Kim": "1.girlfriend 從工作的壓力被釋\n放\n2.感謝神 這個禮拜很充實\n開心",
        "Jessie": "",
        "Tom": "",
        "Ryan": "10/25朋友婚禮",
        "Owen": "",
        "Peter": "感謝這一年服事跟\n夥伴相處的都很順利,禱告\n明天即將結婚的夥伴能夠有\n神的祝福,大家恩典都能\n被神繼續帶領祝福,也禱告\n自己跟大家的靈命可以繼續\n成長",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-20",
      "date": "2025-10-16",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "希望忙季可以撐過去",
        "Kim": "",
        "Jessie": "感謝神的幫助！求神繼續保守未來的道路～",
        "Tom": "Regular Sleep schedule, weight loss",
        "Ryan": "Pray for my friend’s wedding next Saturday",
        "Owen": "",
        "Peter": "Pray for my spiritual life can grow more maturely and rest of year keep putting god in my priority. Also thank God recently is going well and smoothly. PTL!!!",
        "Maggie": "感謝主，大考考卷出完、與同事關係稍微改善一些。",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-21",
      "date": "2025-10-23",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": false,
        "Ryan": true,
        "Owen": true,
        "Peter": false,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "下禮拜新的案件可以很順利",
        "Kim": "未來的獨立作業可以順利",
        "Jessie": "持續禱告 親近神",
        "Tom": "",
        "Ryan": "禮拜六朋友的婚禮順利！ 感冒可以好一點",
        "Owen": "頭的包可以快快好起來！",
        "Peter": "",
        "Maggie": "可以和其中兩個同事有共事到的話可以順利",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-22",
      "date": "2025-10-30",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "感謝主的供應 工作 有話語的智慧 不要緊張",
        "Kim": "工作調薪 在新任務 有智慧！",
        "Jessie": "生涯規劃！",
        "Tom": "期中考 轉學的事情 時間的分配",
        "Ryan": "職場上有明確的進展",
        "Owen": "回到服事團隊",
        "Peter": "服事夥伴感恩餐會 新年度的服事",
        "Maggie": "學校節慶/跟同事的關係",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-23",
      "date": "2025-11-06",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "求主帶領工作一切順利；感情求神帶領",
        "Kim": "幫Molly寶貝挑到心儀的禮物；求主帶領並賜智慧在工作上",
        "Jessie": "",
        "Tom": "求主帶領轉學考一切順利，能在主裡安息",
        "Ryan": "希望主能帶領他找到適合的工作",
        "Owen": "組聚烤肉順利",
        "Peter": "求主保守賜給他智慧找到工作和服事的平衡，讓他努力工作之餘，也能在主裡好好休息",
        "Maggie": "求主幫忙帶領工作順利，與同事好好相處；屬靈的生命成長",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-24",
      "date": "2025-11-13",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": false,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "愛情💓， 工作完成。",
        "Kim": "工作中有智慧， 有個清楚的腦袋，適時的玩switch,不要玩太多。",
        "Jessie": "",
        "Tom": "",
        "Ryan": "求職有進展，另一伴。",
        "Owen": "另一伴， 服事。",
        "Peter": "為自己的身體健康，聖誕節服事！",
        "Maggie": "繼續為職場和爸爸媽媽的健康，屬靈上的成長， 另外一半。",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-25",
      "date": "2025-11-27",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "愛情💓、明天績效訪談、forward禱告",
        "Kim": "右眼長針眼、跟討厭的同事關係有神緩和、工作有智慧",
        "Jessie": "禮拜六工作辦理志工培訓（實習工作）求神給我強壯的精神和體力",
        "Tom": "爸媽的健康",
        "Ryan": "forward禱告、對2026盼望與期待",
        "Owen": "forward禱告以及奉獻數字背後的意義",
        "Peter": "體力與身體健康、受傷的背、2026大家對上帝的盼望與期待",
        "Maggie": "寒假好好休息、身體禱告",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-26",
      "date": "2025-12-04",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "感謝神本季工作績效第一名、求神看顧上海出差一路平安",
        "Kim": "感謝神身體有漸漸好轉、求神醫治降血壓",
        "Jessie": "",
        "Tom": "感謝神有變瘦、求申請學校順利",
        "Ryan": "感謝神本周很順利、求活出restore的道/工作",
        "Owen": "感謝神工作備受主管關注栽培、求神看顧家人日本旅行一路平安",
        "Peter": "感謝神本周很順利、求神醫治背部恢復健康",
        "Maggie": "感謝神課程設計順利、求順利活過期末",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-27",
      "date": "2025-12-11",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作",
        "Kim": "身體健康",
        "Jessie": "期末考",
        "Tom": "期末考、面對成績的災禍",
        "Ryan": "",
        "Owen": "",
        "Peter": "12月好好準備好這次的服事",
        "Maggie": "喉嚨好一點求神醫治",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-28",
      "date": "2025-12-18",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": false,
        "Kim": false,
        "Jessie": true,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": false,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "",
        "Kim": "",
        "Jessie": "抓住機緣",
        "Tom": "未來",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "希望可以跟同事妥協，希望上帝，打來給學生最好的結果。讓自己得到安寧。",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-29",
      "date": "2025-12-25",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": false,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作狀況禱告、感情禱告",
        "Kim": "感情",
        "Jessie": "",
        "Tom": "作業寫完、未來清晰一點、不要這麼徬徨且茫然要有盼望、可以度過身邊的挑戰、知道怎麼把自己的想法說出來",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "帶課的靈感（期末）、寒假好好的休息、教甄預備",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-30",
      "date": "2026-01-01",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": true,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": false,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作感情",
        "Kim": "",
        "Jessie": "未來的方向",
        "Tom": "轉學申請結果順利",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-31",
      "date": "2026-01-16",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "尾牙大獎  讀經順利  愛情",
        "Kim": "讀經挑戰順利",
        "Jessie": "生理期順利\n                  面試順利",
        "Tom": "轉學順利",
        "Ryan": "簽證順利下來",
        "Owen": "尾牙中大將",
        "Peter": "感謝神 環境很棒\n             挑戰新約  讀完",
        "Maggie": "課程順利",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-32",
      "date": "2026-01-22",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "自己的時間規劃可以順利實行、瘦一點",
        "Kim": "肝指數下降",
        "Jessie": "感謝到花蓮認識基督徒聊很多因此看見屬靈生命的見證，面試順利",
        "Tom": "找工作",
        "Ryan": "休息的時間很多很感謝神、為簽證順利",
        "Owen": "為尾牙偏財禱告  理性飲酒",
        "Peter": "休息的時間很多很感謝神、讀經的習慣",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-33",
      "date": "2026-01-29",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": false,
        "Ryan": false,
        "Owen": false,
        "Peter": false,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "感謝獲財能力、愛情解決",
        "Kim": "肝指數、拉肚子",
        "Jessie": "",
        "Tom": "",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "感謝神出國平安天氣好心情好、好好休息、外師合作順利、教甄準備、備課預備",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-34",
      "date": "2026-02-05",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": false,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "感謝股票，代禱比特幣、工作突發問題、感情",
        "Kim": "感謝這禮拜很紮實在工作，代禱尾牙抽獎*4",
        "Jessie": "尾牙喝好多酒，感謝同事幫忙，代禱生涯規劃可以有神的帶領",
        "Tom": "",
        "Ryan": "感謝刮刮樂，代禱簽證澳洲，愛情",
        "Owen": "感謝上帝工作有點輕鬆，工作順利到過年，明天echo大大領受，愛情",
        "Peter": "感恩要過年趕快放假，代禱有一個好的休息",
        "Maggie": "感恩神上禮拜與團契交通感情的故事，有肢體陪伴，代禱男友沒有很長的時間認識，所以很不安，希望神把平安放進裡面，昨日有些小落空，希望這份小擔心不要太緊張",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-35",
      "date": "2026-02-12",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": false,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "代禱工作忙季好忙希望能熬過來，感情能被神帶領，不要再憑著自己的感受",
        "Kim": "家庭家人的健康還有身心靈",
        "Jessie": "校隊寒訓，身體雖然累但很紮實，所以感謝神，代禱明天的訓練順利結束，好年",
        "Tom": "感恩有上班穩定收入，代禱爸媽年長了所以健康，也代禱自己不要當啃老族",
        "Ryan": "感謝代禱簽證補件順利也成功下來",
        "Owen": "感謝主管年終有點嚇到，代禱又要去墨西哥，三月初去保守安全",
        "Peter": "",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-36",
      "date": "2026-03-05",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": false,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "工作壓力以及任務完成",
        "Kim": "工程順利，解決事情的智慧",
        "Jessie": "工作很忙，隊上成員傷勢復原，可以早日康復",
        "Tom": "",
        "Ryan": "",
        "Owen": "",
        "Peter": "感謝這陣子有好的休息，穩定的服事，保持讀經",
        "Maggie": "開學很順利，代禱少子化學校減班會砍老師，希望工作穩穩妥妥。考試順利禱告，也為同事關係禱告。",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-37",
      "date": "2026-03-12",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": true,
        "Owen": false,
        "Peter": false,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "為工作順利禱告以及偏財運禱告",
        "Kim": "為工作順利禱告以及闔家平安",
        "Jessie": "",
        "Tom": "為找工作禱告",
        "Ryan": "為簽證禱告",
        "Owen": "",
        "Peter": "",
        "Maggie": "為教徵考試禱告",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-38",
      "date": "2026-03-19",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": false,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "為身體骨折禱告以及都沒運動不要胖胖",
        "Kim": "工作順利",
        "Jessie": "最近過的好舒服，代禱為小組大家順順利利",
        "Tom": "爸媽的健康，暑修選的到課",
        "Ryan": "感謝神大腸鏡檢查沒問題，胃鏡禱告以及簽證",
        "Owen": "出差順利",
        "Peter": "",
        "Maggie": "身體健康",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-39",
      "date": "2026-03-26",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "手的狀況以及出國平安、減肥",
        "Kim": "為出國泰國旅程平安，工作順利",
        "Jessie": "",
        "Tom": "減肥",
        "Ryan": "這兩週腸鏡胃鏡順利，代禱簽證順利",
        "Owen": "",
        "Peter": "最近工作比較忙希望這陣子工作生活服事找到平衡，可以安排好自己的時間",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-40",
      "date": "2026-04-02",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": false,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "泰國旅遊很黑皮(快樂)、手臂比想像更嚴重，希望快好一點。下週工作要被約談，希望順利",
        "Kim": "泰國旅遊",
        "Jessie": "校隊隊員的身體健康",
        "Tom": "減肥、時間管理",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "雙北教甄、感情磨合",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-41",
      "date": "2026-04-09",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "下禮拜要跟會計師開會求神保守、手可以修復",
        "Kim": "儀器可以找回，工作可以順遂",
        "Jessie": "",
        "Tom": "代禱期中考順利、睡飽",
        "Ryan": "感謝工作很忙很充實，為簽證代禱在上帝安排的時間",
        "Owen": "",
        "Peter": "工作比較忙碌，代禱有更多的智慧求神保守",
        "Maggie": "代禱老師考試，準備考試有平安的心",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-42",
      "date": "2026-04-16",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": false,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "感謝會議順利，下禮拜還是要會議需要代禱",
        "Kim": "感謝儀器找到了，代禱工作順利",
        "Jessie": "為我的同事代禱認識這份信仰，這禮拜那位同事來到主日有大大領受",
        "Tom": "",
        "Ryan": "感謝這禮拜很順遂，代禱不要靠自己點的光往前，要依靠上帝帶領",
        "Owen": "",
        "Peter": "為這禮拜服事代禱，要負責帶領著整個兒主，有神帶領",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-43",
      "date": "2026-04-23",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "為手臂肌肉復健禱告",
        "Kim": "感謝神工作上公安事故化險為夷，代禱工程順利",
        "Jessie": "為下週柔道比賽，以及為身體小感冒禱告",
        "Tom": "代禱爸媽的健康",
        "Ryan": "為參加特會的人的心禱告，感謝上帝簽證下來希望上帝保守下一步",
        "Owen": "",
        "Peter": "感謝主上禮拜服事順利會議很順利，代禱為特會的心禱告",
        "Maggie": "為身體禱告，喉嚨醫治，在學校工作可以降低使用喉嚨，教師考試順利。",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-44",
      "date": "2026-05-07",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "復健、明天面試以及工作安排、考美國會計師",
        "Kim": "在工作跟感情有智慧，工作上進度緩慢，很累的時候沒有能量處理感情",
        "Jessie": "",
        "Tom": "交朋友代禱",
        "Ryan": "",
        "Owen": "",
        "Peter": "讀經可以持續穩定、大家可以好好珍惜跟瑞恩相處的時間",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-45",
      "date": "2026-05-14",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": true,
        "Tom": false,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "復健、準備考試",
        "Kim": "",
        "Jessie": "感謝剛比完賽有一種重現巡邏的動力，隊友骨折康復有的好醫治",
        "Tom": "",
        "Ryan": "",
        "Owen": "",
        "Peter": "跟瑞恩感傷的分別順順利利",
        "Maggie": "準備考試",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-46",
      "date": "2026-05-21",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": true,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": false,
        "Shire": false,
        "Grace": false
      },
      "prayers": {
        "Zachary": "感謝工作開始充實，代禱工作順利生活順順利利，手手康復成功",
        "Kim": "",
        "Jessie": "感謝這禮拜雖然有一件讓人挫折，但有美好的結尾，代禱下禮拜柔道分段考試",
        "Tom": "代禱期末報告，感恩媽咪出院",
        "Ryan": "",
        "Owen": "",
        "Peter": "工作開始比較忙，所以代禱服事上的調整與生活上的平衡，瑞恩平安降落，還有未來愛情旅程",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-47",
      "date": "2026-05-24",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": true,
        "Shire": true,
        "Grace": true
      },
      "prayers": {
        "Zachary": "",
        "Kim": "",
        "Jessie": "",
        "Tom": "",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-48",
      "date": "2026-05-28",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": true,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": true,
        "Shire": true,
        "Grace": true
      },
      "prayers": {
        "Zachary": "代禱工作",
        "Kim": "感謝這禮拜買外套，為明天開車禱告",
        "Jessie": "感謝帶志工有感動分享，代禱小畢典順順利利",
        "Tom": "學期末趕報告，代禱可以把事情做完",
        "Ryan": "感謝穩妥抵達澳洲，寄宿的家人很照顧，明天要試新車，感謝來到澳洲追求愛情成功了，禮拜五禮拜天開長途禱告",
        "Owen": "感恩讀到這一章節，因為摩西跟平凡人一樣，但展現信心的操練，小小的信心大大的勇氣。代禱又要去出差了，需要平安的過程",
        "Peter": "工作忙碌以及主日學服事需要分散時間，要有平衡",
        "Maggie": "",
        "Simone": "代禱因為最近接近學期末，所以小孩比較浮躁，希望能夠順利穩穩帶小孩子",
        "Shire": "這幾個禮拜新工作，有新的東西需要神的智慧，明天要是生日",
        "Grace": "八月要去澳洲，希望可以順利準備澳洲"
      }
    },
    {
      "id": "meeting-49",
      "date": "2026-05-31",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": false,
        "Tom": false,
        "Ryan": false,
        "Owen": false,
        "Peter": false,
        "Maggie": true,
        "Simone": true,
        "Shire": true,
        "Grace": false
      },
      "prayers": {
        "Zachary": "",
        "Kim": "",
        "Jessie": "",
        "Tom": "",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-50",
      "date": "2026-06-04",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": true,
        "Jessie": true,
        "Tom": true,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": true,
        "Shire": true,
        "Grace": false
      },
      "prayers": {
        "Zachary": "感謝父母願意認識信仰，代禱父母福音準備考試跟工作順利",
        "Kim": "平安喜樂",
        "Jessie": "旅遊平安愉快",
        "Tom": "為媽媽健康禱告，兩三個禮拜會去醫院，希望上帝醫治媽媽的免疫系統（全身紅斑性狼瘡）",
        "Ryan": "",
        "Owen": "",
        "Peter": "家庭有些事情，我們相信上帝是一家之主，所以禱告神帶領彼得家庭順利度過",
        "Maggie": "",
        "Simone": "希望能夠未來來到班級的小孩符合神的心意",
        "Shire": "為工作禱告",
        "Grace": ""
      }
    },
    {
      "id": "meeting-51",
      "date": "2026-06-11",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": false,
        "Tom": true,
        "Ryan": false,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": true,
        "Shire": true,
        "Grace": false
      },
      "prayers": {
        "Zachary": "準備考試、復健最後一哩路，朋友教檢順利",
        "Kim": "",
        "Jessie": "",
        "Tom": "期末考希望順順利利，為母親身體代禱",
        "Ryan": "",
        "Owen": "挺感謝現在生活規律，工作生活有平衡，代禱我們公司私下約出去玩希望順利建立美好關係",
        "Peter": "家庭順利",
        "Maggie": "教甄",
        "Simone": "該做的事趕快做完，趕快迎接暑假",
        "Shire": "工作這幾天遠端工作配合老闆，之前工作機會找他們聊一聊，需要智慧與他們聊",
        "Grace": ""
      }
    },
    {
      "id": "meeting-52",
      "date": "2026-06-14",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": false,
        "Tom": false,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": false,
        "Simone": true,
        "Shire": true,
        "Grace": true
      },
      "prayers": {
        "Zachary": "",
        "Kim": "",
        "Jessie": "",
        "Tom": "",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-53",
      "date": "2026-06-18",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": false,
        "Tom": true,
        "Ryan": false,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": false,
        "Shire": true,
        "Grace": true
      },
      "prayers": {
        "Zachary": "我社群媒體救回來，考試",
        "Kim": "",
        "Jessie": "",
        "Tom": "希望不要被當",
        "Ryan": "",
        "Owen": "健康檢查報告出爐一切正常",
        "Peter": "去花蓮平安",
        "Maggie": "考完教甄，希望順利正取到交通距離合適的學校，以及分發前的心情",
        "Simone": "",
        "Shire": "老闆道德有點瑕疵，希望可以順利換合作方式，願接下來會有恩典與亮光，而不是下一個坑",
        "Grace": "澳洲規劃希望能學會手放開，以及有智慧整理行李"
      }
    },
    {
      "id": "meeting-54",
      "date": "2026-06-25",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": true,
        "Tom": false,
        "Ryan": false,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": true,
        "Shire": true,
        "Grace": true
      },
      "prayers": {
        "Zachary": "這週工作爆多但順利，保險下來了，準備考試",
        "Kim": "",
        "Jessie": "感謝這週很充實，期待畢業到下一個階段，希望神的帶領坐在培訓期",
        "Tom": "",
        "Ryan": "",
        "Owen": "感謝上帝一切順遂，代禱這禮拜針眼很痛希望上帝醫治",
        "Peter": "代禱服事跟工作得道力量",
        "Maggie": "感謝新北考上了，代禱志願分發安排，到新的學校是善待老師以及家長良善",
        "Simone": "這週非常忙碌但很順利，演釋非常順利小孩很穩，代禱這學期順順",
        "Shire": "明天品酒會，希望代禱營業額保守神的祝福，十萬",
        "Grace": "澳洲安排順利"
      }
    },
    {
      "id": "meeting-55",
      "date": "2026-06-28",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": false,
        "Tom": false,
        "Ryan": false,
        "Owen": true,
        "Peter": true,
        "Maggie": true,
        "Simone": true,
        "Shire": true,
        "Grace": true
      },
      "prayers": {
        "Zachary": "",
        "Kim": "",
        "Jessie": "",
        "Tom": "",
        "Ryan": "",
        "Owen": "",
        "Peter": "",
        "Maggie": "",
        "Simone": "",
        "Shire": "",
        "Grace": ""
      }
    },
    {
      "id": "meeting-56",
      "date": "2026-07-02",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": false,
        "Tom": true,
        "Ryan": false,
        "Owen": true,
        "Peter": true,
        "Maggie": false,
        "Simone": true,
        "Shire": true,
        "Grace": false
      },
      "prayers": {
        "Zachary": "感恩本週工作順利，祝福竣文在神的帶領",
        "Kim": "",
        "Jessie": "",
        "Tom": "感恩有錢錢了，代禱工作順利",
        "Ryan": "",
        "Owen": "代禱我家人這禮拜去泰國，有出現意外從大象掉下來，希望神醫治",
        "Peter": "感恩最近感謝主在工作方面有一個平衡，代禱在服事需要平衡也找到自己的節奏，在服事上可以得著力量",
        "Maggie": "",
        "Simone": "這個禮拜很感謝主很蒙福在求職有滿滿的準備，求主有智慧可以看見哪一個符合神喜悅的，在選項中依然可以選擇榮耀神服事神",
        "Shire": "外婆癌症 代禱身體健康",
        "Grace": ""
      }
    },
    {
      "id": "meeting-57",
      "date": "2026-07-09",
      "topic": "",
      "scripture": "",
      "location": "",
      "notes": "",
      "attendance": {
        "Zachary": true,
        "Kim": false,
        "Jessie": false,
        "Tom": false,
        "Ryan": false,
        "Owen": false,
        "Peter": true,
        "Maggie": true,
        "Simone": true,
        "Shire": true,
        "Grace": false
      },
      "prayers": {
        "Zachary": "業與工作平衡安排，有智慧與自制力過每一天",
        "Kim": "",
        "Jessie": "",
        "Tom": "",
        "Ryan": "",
        "Owen": "",
        "Peter": "服事的平衡，為休息禱告",
        "Maggie": "最近很焦慮，未來要教四個年段，所以工作量好大，希望神帶領效率提升，可以有體力跟靈感完成備課，同時也可以適應同儕跟小孩，也願工作環境有神的保守溫溫和和；舅舅癌症開刀也需要神的保守",
        "Simone": "外婆癌症需要神的帶領，在過程中減緩痛苦",
        "Shire": "工作找到了，這個月蠻恩典的很多機會，神有美好的帶領，願接下來的工作負荷神的心意，與可以為神發光發熱",
        "Grace": ""
      }
    }
  ],
  "interviews": [],
  "updatedAt": "2026-07-12T08:35:12.841797"
};
